x = int(input('Input first number: '))
y = int(input('Input second number: '))
print(' ')
print('Addition:', x + y)
print('Substraction:', x - y)
print('Multiplication:', x * y)
print('Division:', x / y)
print('Modulus:', x % y)
print('Exponentiation:', x ** y)
print('Floor division:', x // y)